config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "filter", to: "posts#filter"
  get "search", to: "posts#search"

  resources :posts do
    resources :comments
    resources :likes
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  
  has_and_belongs_to_many :tags
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user

  scope :search_result, ->(parameter) { where("lower(title) LIKE :search", search: "%#{parameter}%") }

  def self.filter_posts_by_tags(tag)
    Tag.find_by(title: tag).posts
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to posts_path(@post)
  end

  private
    def comment_params
        params.require(:comment).permit(:user_id, :body)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post

  def create
    if !(already_liked?)
        @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  private 
  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[ index ]

  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  def search
    if params[:search].blank?
      redirect_to root_path and return
    else
      @parameter = params[:search].downcase
      @results = Post.search_result(@parameter)
    end
  end

  def filter
    @results = Post.filter_posts_by_tags(params[:tag_title])
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @tags = Tag.all
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :title, :content, {tag_ids:[]})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="card">
    <div class="card-header">
        <span class="comment-name"><%= comment.user.email %></span>
        <span class="comment-date"><%= comment.created_at.strftime("%Y-%m-%d") %></span>
    </div>
    <div class="card-body">
        <p><%= comment.body %></p>
    </div>
</div>
<br>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
    <p class="field form-group">
    <%= form.text_field :user_id, id: :comment_user_id, type: :hidden, value: current_user.id, class: "form-control" %>
    </p>
    <p class="field form-group">
    <%= form.label "Write your comment" %>
    <%= form.text_area :body, class: "form-control" %>
    </p>
    <p class="field form-group">
    <%= form.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">  

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "posts/header" %>
    <div class="container ml-1">
      <br>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :user_id, id: :post_user_id, value: current_user.id, type: :hidden, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <%= collection_check_boxes(:post, :tag_ids, Tag.all, :id, :title) do |b| %>
    <div class="field form-group">
      <%= b.check_box class: "checkbox-container" %>
      <%= b.label class: "checkbox-container" %> 
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>

  <%= link_to "Home", root_path, class: "return-inline" %>
<% end %>

app/views/posts/_header.html.erb
<nav class="navbar navbar-expand-sm py-4 navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Medium-clone", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "New Post", new_post_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sing Up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>

        <%= form_tag( search_path , :method => "get", :class => "d-flex") do %>
        <div class="input-group">
          <%= search_field_tag :search, params[:search], placeholder: "Search",
          class: "form-control me-2" %>
            <div class="input-group-btn">
              <%= button_tag "Search", :class => "btn btn-outline-success",
              :name => nil %>
            </div>
        </div>
        <% end %>
        
      </div>

  </div>
</nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/filter.html.erb
<div class="search-results-container">
    <h1>Search results</h1>

    <% if @results.any? %>
        <% @results.each do |result| %>
            <h3><%= link_to result.title.to_s, result %></h3>
        <% end %>
    <% else %>
        <h3>Sorry, we've found nothing. Try again. Maybe you need to fix some typos?</h3>
    <% end %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% if @posts.any? %>
  <h1>Posts</h1>
  <% @posts.each do |post| %>
    <div class="card">
      <div class="card-header">
        <h5 class="text-muted">By <%= post.user.email %></h5>
        <h6 class="text-muted">Created at <%= post.created_at.strftime("%Y-%m-%d") %></h6>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= post.title %></h5>
        <p class="card-text"><%= post.content %></p>
        <p><%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
        <%= link_to 'Show', post, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %>
        <%= link_to 'Destroy', post, method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure?' } %>
      </div>
      <div class="card-footer">
        <ul class="list-inline">
          <% post.tags.each do |tag| %>
              <li class="list-inline-item">
                <%= link_to tag.title, filter_path(tag_title: tag.title)%>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
    <br>
  <% end %>
<% else %>
  <div class="show-no-posts">
    <h2>Sorry we haven`t posts yet</h2>
    <br>
    <br>
    <h3><%= link_to "Add the first one", new_post_path %></h3>
  </div>
<% end %>

<% if @posts.all.count > 5 %>
  <div class="apple_pagination">
    <%= will_paginate @posts, :container => false %>
  </div>
<% end %>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/search.html.erb
<div class="search-results-container">
    <h1>Search results</h1>

    <% if @results.any? %>
        <% @results.each do |result| %>
            <h3><%= link_to result.title.to_s, result %></h3>
        <% end %>
    <% else %>
        <h3>Sorry, we've found nothing. Try again. Maybe you need to fix some typos?</h3>
    <% end %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <div class="card-header">
    <h5 class="text-muted">By <%= @post.user.email %></h5>
    <h6 class="text-muted">Created at <%= @post.created_at.strftime("%Y-%m-%d") %></h6>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @post.title %></h5>
    <p class="card-text"><%= @post.content %></p>
    <%= link_to 'Like', post_likes_path(@post), method: :post, class: "btn btn-info" %>
    <p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <%= link_to 'Show', @post, class: "btn btn-primary" %>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %>
    <%= link_to 'Destroy', @post, method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure?' } %>
    <%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>
  </div>
  <div class="card-footer">
    <ul class="list-inline">
      <% @post.tags.each do |tag| %>
          <li class="list-inline-item">
            <%= link_to tag.title, filter_path(tag_title: tag.title)%>
          </li>
      <% end %>
    </ul>
    <hr>

    <h2>Comments</h2>
    <%= render @post.comments %>

    <h2>Add a comment:</h2>
    <%= render "comments/form" %>

  </div>
</div>
<br>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>